### PR TITLE
Remove Cors Config and update dependencies

### PR DESCRIPTION
**Pull request by nikosnikolaidis**

### CODE REVIEW

**Comment by deanone** [comment]
@nikosnikolaidis a review is required for ths PR to be merged. Do you want me to do it?

**Comment by nikosnikolaidis** [comment]
@deanone Some checks haven't finished yet. So lets wait a bit.

**Comment by nikosnikolaidis** [comment]
@deanone These checks haven't completed yet.
Do you know why?

**Review by deanone — DISMISSED** [review]

**Comment by deanone** [comment]
@nikosnikolaidis any PR needs at least one review from someone other that the author. I just approved the changes in this PR.

**Review by deanone — APPROVED** [review]

**Comment by nikosnikolaidis** [comment]
Fixed with #28

**Pull request closed without merging**
